name: automerge
on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: automerge
        uses: ./.github/actions/automerge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
